# managedfileservice-compose.yml - Using shared database

version: '3.8'

services:
  # Volume initialization container
  init-volume:
    image: busybox
    command: chmod -R 777 /app/uploads
    volumes:
      - upload_storage:/app/uploads
    restart: "no"
    
  # Application Service
  managedfileservice:
    container_name: managedfileservice-app
    image: managedfileservice
    build:
      context: .
      dockerfile: ManagedFileService/Dockerfile
    ports:
      - "7100:8080"
    volumes:
      - upload_storage:/app/uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # Updated to point to the shared database service
      - ConnectionStrings__DefaultConnection=Server=shared-postgres;Port=5432;Database=ManagedFileService;User Id=digital;Password=digital;Trust Server Certificate=True;
      - FileStorage__BasePath=/app/uploads
      - ASPNETCORE_URLS=http://+:8080
      - SignedUrlSettings__SecretKey=${SIGNED_URL_SECRET_KEY:-DefaultDevSecretKeyWhichIsNotSecureAtAllAndNeedsReplacing}
      - SignedUrlSettings__MaxExpiryMinutes=10080
    depends_on:
      init-volume:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - default
      - shared-db-network

# Named Volumes Definition
volumes:
  upload_storage:
    driver: local

# Use the shared network to connect to the database
networks:
  default:
    driver: bridge
  shared-db-network:
    external: true
    name: shared-db-network